// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCic7jIFRGHjTtLRE9CwkkxBJqjLbquZs',
    appId: '1:861172355215:web:c1ccf13177b48025a220fa',
    messagingSenderId: '861172355215',
    projectId: 'glow-guide-50e69',
    authDomain: 'glow-guide-50e69.firebaseapp.com',
    storageBucket: 'glow-guide-50e69.appspot.com',
    measurementId: 'G-ZCKNP1YVGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCYoIs8sHD22VoPwiUAS53AzdPzMJWIA',
    appId: '1:861172355215:android:c6df0e949f673f3da220fa',
    messagingSenderId: '861172355215',
    projectId: 'glow-guide-50e69',
    storageBucket: 'glow-guide-50e69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_QGtbXhWeP5x9DohNl_bGefegqk2f7Q',
    appId: '1:861172355215:ios:19f87612af113618a220fa',
    messagingSenderId: '861172355215',
    projectId: 'glow-guide-50e69',
    storageBucket: 'glow-guide-50e69.appspot.com',
    iosBundleId: 'com.example.glowGuideProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO_QGtbXhWeP5x9DohNl_bGefegqk2f7Q',
    appId: '1:861172355215:ios:19f87612af113618a220fa',
    messagingSenderId: '861172355215',
    projectId: 'glow-guide-50e69',
    storageBucket: 'glow-guide-50e69.appspot.com',
    iosBundleId: 'com.example.glowGuideProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCic7jIFRGHjTtLRE9CwkkxBJqjLbquZs',
    appId: '1:861172355215:web:b5cb2d1e4e81f9a9a220fa',
    messagingSenderId: '861172355215',
    projectId: 'glow-guide-50e69',
    authDomain: 'glow-guide-50e69.firebaseapp.com',
    storageBucket: 'glow-guide-50e69.appspot.com',
    measurementId: 'G-YE487XJQJL',
  );
}
